#!/bin/bash

# Remove Nomendex (production) from Applications and user data

echo "Removing Nomendex from /Applications..."
rm -rf /Applications/Nomendex.app

echo "Removing user data from ~/Library/Application Support..."
rm -rf ~/Library/Application\ Support/com.firstloop.nomendex

echo "Done! Nomendex and all user data have been removed."
