services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: nomendex
      POSTGRES_PASSWORD: nomendex
      POSTGRES_DB: nomendex_team
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
